### ISSUE TITLE
투네이션은 alertbox 접근하면 block 하는군요

### ISSUE THREAD

**Issue by jamesleegit** [nomomo/Twip-Toonation-Afreehp-Parser-Example#3]
문의 해보니 직접연결해서 사용하지말라고 답변받았네요.

**Comment by nomomo** [comment]
안녕하세요.

일단 제가 올려준 코드로 안 좋은 일이 생기신 것 같아 죄송하다는 말씀을 드리고요,
올려둔 코드처럼 12초 핑 간격으로 단순히 메시지를 읽어오기만 하는 경우 지금까지는 문제가 없었습니다만,
문제가 생기신 경우 사용하지 않는 것이 좋으시겠습니다.

Alertbox 페이지에 JavaScript 를 Injection 해서 WebSocket 의 addEventListener 함수를 override 하는 방법으로 메시지를 빼오면 연결 등 모든 것이 원래 투네이션의 방법을 따르므로 문제가 없을 듯 합니다.
XSplit 의 경우 자체적으로 JavaScript injection 이 가능하니 XSplit 을 사용하시거나, 크로미움 같은 걸로 돌리셔도 될듯합니다.
