### ISSUE TITLE
질문] 전체채팅 내용도 불러올 수 있을까요 ?

### ISSUE THREAD

**Issue by cha2hyun** [nomomo/Twip-Toonation-Afreehp-Parser-Example#4]
안녕하세요. 소켓통신 공부하면서 만들어주신 프로그램 실행해서 이것 저것 많이 도움이 되고 있습니다. 감사합니다. 

### 궁금한점 
후원 뿐만 아니라 **아프리카 도우미의 모든 채팅 내용**을 받아보는 법이 궁금합니다.

### 해본것

1. 콘솔 찍어보니 `socketAfreehp.on("cmd", ..)`에서는 후원 관련 내용만 불러와지는 것 같았습니다. ( 정확히는 `type: 'testmsg`만 성공하였습니다). 

2. 혹시 아래 `connect`이벤트에서 emit 할때 `page` 부분을 변경하면 채팅까지 불러와질 수 있을까 하여 몇가지 시도해 보았으나 성공하지 못했습니다.
    ```js
     socketAfreehp.on("connect", function () {
            console.log("Afreehp Connected");
            socketAfreehp.emit("page", page);
             ....
    }
    ```

3. 알럿박스 url의 소스도 확인해 보고 콘솔도 찍어봤으나 후원이 아닌 평문 메세지에는 반응하지 않았습니다.
    <img width="1217" alt="image" src="https://user-images.githubusercontent.com/56015532/226250173-6c4453b5-3810-4f7a-8428-067e8df884fe.png">

4. 하단 소스 이용하여 모든 소켓 이벤트 확인해 보았으나 텍스트에선 아무 반응이 없지만 후원에만 반응이 있었습니다.
    ```js
    var onevent = socketAfreehp.onevent;
    socketAfreehp.onevent = function (packet) {
      var args = packet.data || [];
      onevent.call(this, packet); // original call
      packet.data = ["*"].concat(args);
      onevent.call(this, packet); // additional call to catch-all
    };
    socketAfreehp.on("*", function (event, data) {
      console.log("이벤트명", event, data);
    });
    ```

5. 알럿박스 url 네트워크 탭에서 확인해 보니 메세지 영역은 아예 별개의 url에서 받아오는 것 으로 예상되었습니다. 텍스트만 작성시 8000 포트로 연결된 소켓에서만 응답이 있었으며,  후원 시에는 반대로 아무런 반응이 없었습니다.  **(Request Url : ws://110.10.76.66:8000/Websocket)**
    <img width="515" alt="image" src="https://user-images.githubusercontent.com/56015532/226272100-c0d0828a-5f1d-471d-b038-df4a9be22308.png">

6. 바이너리 코드를 base64로 복사하여 utf-8 디코드 하니 원문 메세지를 확인할 수 있었습니다.
    ![image](https://user-images.githubusercontent.com/56015532/226272461-95bde320-1695-4b3c-a87a-fe5ba3fa904b.png)

7. 다만 5번 6번은 도우미 > 아프리카TV 연결일 수 있다는 생각이 들었습니다.

8. 아프리카티비, 유튜브를 포함한 통합 채팅내용, 즉 도우미의 채팅창 url의 모든 메세지를 긁고 싶은데 여기서 막혔습니다. 
9. Connect.js 에서 console.log 찍어보면 후원은 표시되지 않고 평문 메세지만 표시되는 것을 확인했습니다.
    <img width="995" alt="image" src="https://user-images.githubusercontent.com/56015532/226278643-c6ec8748-21cb-4491-b698-a17c57b338e8.png">
    <img width="1263" alt="image" src="https://user-images.githubusercontent.com/56015532/226278804-7513d7c9-ec31-4427-af86-dd455e6072cb.png">
10. 다만 만들어주신 코드의 'cmd'를 기다리는 event에서는 표시되지 않습니다..

몇가지 팁을 알고 계시면 공유부탁드려도 될까요? 🙇‍♂️

**Comment by nomomo** [comment]
안녕하세요. 말씀해주신 내용을 요약하자면 "아프리카 도우미에서 출력되는 여러 플랫폼의 채팅 내역을 한 번에 파싱" 이라고 정리할 수 있을 것 같습니다. 대충 코드를 봤는데 100% 확실하지는 않지만 아프리카 도우미는 Afreeca, Twitch, Youtube 채팅을 따로따로 연결한 다음, 합쳐서 보여주는 것으로 보입니다.

이를 직접 구현하려면 방법은 두 가지가 있을 것 같습니다.
1. 아프리카 도우미처럼 Youtube, Twitch, Afreecatv 따로 연결해서 채팅을 긁어옵니다. Youtube 와 Twitch 의 경우 API 가 너무 잘 되어있으므로 가져오기 쉽습니다. Afreecatv 의 경우 채팅을 직접 파싱해보지는 않았지만 직접 찾으신 아프리카 도우미의 웹소켓 연결을 사용하면 되지 않을까 합니다.
2. Headless chrome 으로 아프리카 도우미의 채팅 url 에 접속한 후, element 생성을 감지하여 파싱합니다.

저는 개인적으로 가지고 노는 프로젝트의 경우에는 두 번째와 같은 방법을 선호하는데, 눈에 보이는 html 구조만 파악하면 되므로 구현이 아주 쉽기 때문입니다.

다음은 이를 위한 sample 코드입니다.
```node.js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        // 크롬 창을 띄우지 않으려면 true 로 변경
        headless: false
    });
    const page = await browser.newPage();
    await page.goto('/*여기에 아프리카도우미 채팅창 url 입력(alertbox url 아님!!!) */');
    await page.exposeFunction('getItem', function(a) {
        // 여기서 원하는 것을 실행. 현재는 콘솔에 출력하도록 되어있음.
        console.log(a);
    });
    await page.evaluate(() => {
        const target = document.querySelector(`div.chat_area`);
        const observer = new MutationObserver(mutations => {
            for (const mutation of mutations) {
                // headless chrome 의 콘솔에 내용 출력
                console.log('Mutation Detected.', mutation);
                // innerHTML 을 getItem 에 넘김
                getItem(mutation.addedNodes[0].innerHTML);
            }
        });
        let option = {
            subtree: true,
            attributes: true,
            childList: true,
            characterData: true
        }
        observer.observe(target, option);
    });

})();
```

위 코드를 실행하여 콘솔에 출력된 결과는 다음과 같습니다.
![image](https://user-images.githubusercontent.com/863079/226354008-2641d2e5-f3c8-4232-8bcd-268e56cb898e.png)

그냥 요런 방법도 있구나~ 라고 알아주시고 상황에 맞는 가장 나이스한 방법을 사용하시면 될 듯합니다.

**Comment by cha2hyun** [comment]
@nomomo 님 안녕하세요 😀

`afreeca, Twitch, Youtube 채팅을 따로따로 연결한 다음, 합쳐서 보여주는 것으로 보입니다` 
그런 구조여서 따로 따로 표시되었던 거였네요. 헷갈리던 부분이었는데 확인해주셔서 감사합니다. 

예제로 보여주신 크롤링도 도움이 많이 되었습니다. 👍
