### ISSUE TITLE
투네이션 연결 오류

### ISSUE THREAD

**Issue by mynam333** [nomomo/Twip-Toonation-Afreehp-Parser-Example#6]
며칠 전부터 투네이션 연결을 시도하면

Toonat Connect Error: Error: connect ETIMEDOUT 58.229.176.195:8071
라고 뜹니다.

확인 부탁드려도 될까요?

**Comment by nomomo** [comment]
웹소켓 주소가 "wss://ws.toon.at/" 로 변경이 되었네요. 주소만 수정해주니 잘 동작하는 것 같습니다. 덕분에 투네이션에 안 쓰고 남아있는 캐시 있는 것도 확인했네요. 확인 감사드려요.
